# Generated by Django 6.1 on 2026-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_order_signed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='execution_status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ongoing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
