from django.utils import timezone
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, Spacer

from core.pdf import items_table, render_pdf

_styles = getSampleStyleSheet()

STATUS_DISPLAY = {
    'pending': ('Pending', 'yellow'),
    'approved': ('Approved', 'green'),
    'rejected': ('Rejected', 'red'),
}

ITEM_STATUS_LABELS = {
    'stock_deducted': 'Stock Deducted',
    'requested': 'Requested',
    'fulfilled': 'Fulfilled',
}


def build_boq_pdf(boq):
    status_label, status_color = STATUS_DISPLAY.get(boq.status, (boq.status.title(), 'default'))
    order = boq.event
    event = order.event

    meta_rows = [
        ('Event', event.name),
        ('Venue', event.venue),
        ('Client', event.client.get_full_name() or event.client.username),
        ('Planner', event.planner.get_full_name() or event.planner.username),
        ('Classification', event.get_classification_display()),
        ('Created By', boq.created_by.get_full_name() or boq.created_by.username),
        ('Created At', timezone.localtime(boq.created_at).strftime('%Y-%m-%d %H:%M')),
        (
            'Approved By' if boq.status == 'approved' else 'Reviewed By',
            (boq.approved_by.get_full_name() or boq.approved_by.username) if boq.approved_by else '—',
        ),
        ('Approved At', timezone.localtime(boq.approved_at).strftime('%Y-%m-%d %H:%M') if boq.approved_at else '—'),
    ]

    items = list(boq.items.select_related('product').all())
    rows = []
    total_qty = 0
    for item in items:
        total_qty += item.quantity_requested
        rows.append([
            item.product.name,
            str(item.quantity_requested),
            ITEM_STATUS_LABELS.get(item.status, item.status.title()),
        ])
    total_row = ['TOTAL', str(total_qty), '']

    table = items_table(
        ['Product', 'Qty', 'Status'],
        rows,
        col_widths=[100 * mm, 30 * mm, 39 * mm],
        right_align_cols=(1,),
        total_row=total_row,
    )

    body = [table]
    if boq.status == 'rejected' and boq.rejection_reason:
        body += [
            Spacer(1, 14),
            Paragraph(f'<b>Rejection reason:</b> {boq.rejection_reason}', _styles['Normal']),
        ]

    return render_pdf(
        title='BILL OF QUANTITIES',
        doc_number=boq.id,
        status_label=status_label,
        status_color=status_color,
        meta_rows=meta_rows,
        body_elements=body,
        generated_at_label=f'Generated by Doves System on {timezone.localtime().strftime("%Y-%m-%d %H:%M")}',
    )
