# Generated by Django 6.1 on 2026-08-26 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_type', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('classification', models.CharField(blank=True, max_length=10)),
                ('content', models.TextField()),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_gate', models.CharField(blank=True, choices=[('order_approval', 'Order Approval'), ('boq_creation', 'BOQ Creation'), ('requisition_processing', 'Requisition Processing')], max_length=30)),
                ('approver_role', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_approvals', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_approvals', to='events.event')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='policies.policy')),
            ],
        ),
    ]
