# Generated by Django 6.1 on 2026-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_boq_approved_at_boq_approved_by_boq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
