from django.utils import timezone
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, Spacer

from core.pdf import items_table, render_pdf

_styles = getSampleStyleSheet()

STATUS_DISPLAY = {
    'draft': ('Draft', 'default'),
    'sent': ('Sent', 'blue'),
    'accepted': ('Accepted', 'green'),
    'rejected': ('Rejected', 'red'),
}


def build_quotation_pdf(quotation):
    status_label, status_color = STATUS_DISPLAY.get(quotation.status, (quotation.status.title(), 'default'))

    meta_rows = [
        ('Client', quotation.inquiry.client_name),
        ('Contact', quotation.inquiry.contact),
        ('Planner', quotation.planner.get_full_name() or quotation.planner.username),
        ('Event', quotation.event_name),
        ('Venue', quotation.venue),
        ('Classification', quotation.get_classification_display()),
        ('Start', timezone.localtime(quotation.date_start).strftime('%Y-%m-%d %H:%M')),
        ('End', timezone.localtime(quotation.date_end).strftime('%Y-%m-%d %H:%M')),
        ('Valid Until', quotation.valid_until.strftime('%Y-%m-%d') if quotation.valid_until else '—'),
    ]

    rows = [
        [item.description, str(item.quantity), f'{item.unit_price:.2f}', f'{item.subtotal:.2f}']
        for item in quotation.items.all()
    ]
    total_row = ['', '', 'TOTAL', f'{quotation.total:.2f}']

    table = items_table(
        ['Description', 'Qty', 'Unit Price', 'Subtotal'],
        rows,
        col_widths=[85 * mm, 20 * mm, 30 * mm, 32 * mm],
        right_align_cols=(1, 2, 3),
        total_row=total_row,
    )

    body = [table]
    if quotation.notes:
        body += [Spacer(1, 14), Paragraph(f'<b>Notes:</b> {quotation.notes}', _styles['Normal'])]

    return render_pdf(
        title='QUOTATION',
        doc_number=quotation.id,
        status_label=status_label,
        status_color=status_color,
        meta_rows=meta_rows,
        body_elements=body,
        generated_at_label=f'Generated by Doves System on {timezone.localtime().strftime("%Y-%m-%d %H:%M")}',
    )
