# Generated by Django 6.1 on 2026-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_color_product_price_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='missing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='missing_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
